
SWITCH EQU P2.0

SEGMENT0_ENABLE EQU P1.0 
SEGMENT1_ENABLE EQU P1.1
SEGMENT2_ENABLE EQU P1.2
SEGMENT3_ENABLE EQU P1.3

SEGMENT_A EQU P2.0
SEGMENT_B EQU P2.1
SEGMENT_C EQU P2.2
SEGMENT_D EQU P2.3
SEGMENT_E EQU P2.4
SEGMENT_F EQU P2.5
SEGMENT_G EQU P2.6
SEGMENT_DOT EQU P2.7

ORG 0000H
MOV A,00H 
MOV P2,A ;P2 = ""All"" of Port 2 
MOV P1,A

SETB SEGMENT1_ENABLE
SETB SEGMENT_A


END

